export const baseEntries = {
  admin: './admin/admin',
  main: ['./main.js', './main.scss'],
  vendor: ['jquery', 'vue'],
  index: ['./core/index.js', './core/index.scss'],
  heads: ['./head/head.js', './head/head.scss'],
  ['main-page']: './vue-pages/main/main.js',

};
export const entries = {

  contacts: './vue-pages/contacts/contacts.js',
  mortgage: ['./mortgage.js', './mortgage.scss'],
  print: './print/print.scss',
  ['filter-page']: './realty/vue-filter-page.js',
  ['projects-page']: './realty/vue-our-project.js',
  ['project-page']: ['./complex/vue-project-page.js', './complex/project-page.scss'],
  ['trade-in']: './vue-pages/mortgage-pages/vue-trade-in.js',
  ['buy-from-home']: ['./buy-from-home/buy-from-home.js', './buy-from-home/buy-from-home.scss'],
  ['bring-friend']: ['./bring-friend/bring-friend.js', './bring-friend/bring-friend.scss'],
  ['wrong-page']: './core/wrong-page.scss',
  interior: './advantage/interior.js',
  furnishing: './advantage/furnishing.js',
  about: ['./company/about.js', './company/about.scss'],
  domofond: ['./domofond/blocks/domofond.js', './domofond/domofond.scss'],
  customerschool: ['./customer/customerschool.js', './customer/customerschool.scss'],
  tenders: './company/tenders.scss',
  awards: './vue-pages/awards/awards.js',
  education: './vue-pages/education/education.js',
  ['education-events']: './vue-pages/education-events/education-events.js',
  ['education-news']: './vue-pages/education-news/education-news.js',
  ['education-schools']: './vue-pages/education-school/education-schools.js',
  ['education-kindergartens']: './vue-pages/education-kindergartens/education-kindergartens.js',
  ['smart-investment']: './vue-pages/smart-investment/smart-investment.js',
  requisites: ['./company/requisites.js', './company/requisites.scss'],
  services: ['./company/services.js', './company/services.scss'],
  partners: ['./commercial/partners/blocks/partners-intro.scss', './commercial/partners/partners.js'],
  ['for-brokers']: './commercial/partners/blocks/partners-description.scss',
  network: './commercial/partners/blocks/partners-network.scss',
  owners: './commercial/partners/blocks/partners-description-owners.scss',
  docs: ['./docks/docks.js', './docks/docks.scss'],
  media: './contacts/mediapage.scss',
  corporate: './corporate/corporate.scss',
  ['giving-keys']: './realty/giving-keys.scss',
  favorite: './vue-pages/favorite/favorite.js',
  storages: ['./advantage/storages.js', './advantage/storages.scss'],
  sovcom: ['./mortgage/mortgage-sovcom.js', './mortgage/mortgage-sovcom.scss'],
  vtb: ['./mortgage/mortgage-vtb5.js', './mortgage/mortgage-vtb5.scss'],
  weekends: './mortgage/blocks/mortgage-weekends.scss',
  installment: './mortgage/mortgage-installment-plan.scss',
  insurance: './mortgage/insurance.scss',
  leasing: './mortgage/blocks/leasing.scss',
  ['housing-mortgage']: './vue-pages/housing-mortgage/vue-housing-mortgage.js',
  massmedia: ['./press/massmedia-list.js', './press/massmedia.scss'],
  news: ['./press/press-list.js', './press/news-page.scss'],
  ['news-detail']: './press/news-detail.scss',
  ['franchise']: './company/franchise.scss',
  ['franchise-objects']: './company/franchise-objects.scss',
  register: ['./register/register.js', './register/register.scss'],
  ['projects-progress']: './company/projects-progress.scss',
  webcam: ['./advantage/webcam.js', './advantage/webcam.scss'],
  philosophy: './company/philosophy.scss',
  cooperation: './company/cooperation.scss',
  ['promo-detail']: './press/promo-detail.scss',
  ['realty-list']: './realty/realty-list.js',
  manifest: './manifest.scss',
  zorge: './zorge.scss',
  flat: ['./flat/flat-detail.js', './flat/flat.scss'],
  entrances: ['./advantage/entrance-gallery.js', './advantage/entrance-gallery.scss'],
  ['insurance-page']: './company/insurance.scss',
  ['smart-apartment']: ['./vue-pages/smart-apartment/smart-apartment.js'],
  ['living-flats']: ['./realty/living-flats.js', './flat/living-flats.scss'],
  ['vr-tour']: ['./realty/vr-tour-cta.js', './realty/vr-tour-cta.scss'],
  ['vacancy']: './career/vacancy.scss',
  ['subscribed']: './subscription.scss',
  school: ['./school/school.js', './school/school.scss'],
  aero: ['./advantage/aero.js', './advantage/aero.scss'],
  poll: ['./press/poll.js', './press/poll.scss'],
  ['yandex-metro']: './press/yandex-metro.scss',
  ['callback-page']: './press/callback-page.scss',
  ['booking-conditions']: './realty/booking-conditions.scss',
  ['online-booking']: ['./realty/booking-modal.js', './realty/booking-modal.scss'],
  ['com-index']: ['./commercial/core/com-index-new.js', './commercial/core/com-index-2.scss'],
  ['business-platform']: ['./realty/business.js', './realty/business.scss'],
  ['com-complex-list']: ['./commercial/realty/com-complex-list.js', './complex/complex.scss'],
  ['com-project-page']: ['./commercial/core/blocks/com-project-page/com_project_page.js', './commercial/core/com-project-page.scss'],
  //['com-realty-list']: ['./commercial/realty/com-object-list.js', './commercial/realty/blocks/com-realty-list.scss'],
  ['com-filter-page']: './vue-pages/com-filter-page/com-filter-page.js',
  ['com-mortgage']: './vue-pages/business-mortgage/vue-business-mortgage.js',
  ['com-placement']: './vue-pages/placement/vue-com-placement.js',
  compliance: './vue-pages/compliance/compliance.js',
  ['brokerage']: ['./commercial/brokerage/brokerage.js', './commercial/brokerage/brokerage.scss'],
  ['build-to-suit']: ['./commercial/build-to-suit/index.js', './commercial/build-to-suit/build-to-suit.scss'],
  ['rental-business']: ['./commercial/rental-bussines/index.js', './commercial/rental-business-page.scss'],
  ['mortgage-offer']: ['./mortgage/mortgage-comparison-offer.js', './mortgage/mortgage-comparison-offer.scss'],
  ['com-flat']: './commercial/realty/blocks/com-flat.scss',
  ['bk-prokshino']: './vue-pages/bk-prokshino/bk-prokshino.js',
  ['error-404']: './vue-pages/error/vue-error-404.js',
  ['error-404-flat']: './vue-pages/error/vue-error-flat-404.js',
  ['flat-pdf']: './vue-pages/flat-pdf/flat-pdf.js',
  ['flat-page']:'./vue-pages/flat/vue-flat.js',
  certificate: './common/pages/certificate/certificate.scss',
  nalogia: './vue-pages/nalogia/nalogia.js',
  brokerForm: './vue-components/popup/broker-form/vue-form-broker.js',
  newMatCapital: './vue-pages/mortgage-pages/new-mat-capital/new-mat-capital.js',
  ['prokshino-landing']: ['./prokshino-landing/prokshino-landing.js', './prokshino-landing/prokshino-landing.scss'],
  ['parking-page']: ['./vue-pages/parking-page/parking-page.js', './vue-pages/parking-page/parking.scss'],
  assignment: './vue-pages/assignment/assignment.js',
  application: './vue-pages/application/application.js',
  ['realty-zoom-image']:'./realty/realty-zoom-screen.js',
  ['mortgage-detail-page']: './vue-pages/mortgage-detail-page/mortgage-detail-page.js',
  ['com-franchise-info']: './vue-pages/com-franchise/com-franchise.js',
  rentForm: './vue-pages/rent-form/rent-form.js',
  child: './vue-pages/child/child.js',
  ['com-trade-in']: './vue-pages/com-trade-in/com-trade-in.js',
  ['com-3d-tour']: './vue-pages/com-3d-tour/com-3d-tour.js',
  ['prokshino-pdf']: './vue-pages/prokshino-pdf/prokshino-pdf.js',
  //land_dd: './landing-dd.js',
  //land_dd_old: './landing-dd-old.js',
  //masterLanding: ['babel-polyfill','./master-landing.js']
  ['com-filter-404-page']: './vue-pages/error/com-filter-404-page.js',
  gazprombank: './vue-pages/gazprombank/gazprombank.js',
  tradeauto: './vue-pages/tradeIn-auto/tradeauto.js',
};
